### ISSUE TITLE
Please check [task requirements](https://github.com/mate-academy/kt-companion-object). You need to use 'companion object' inside class.

### ISSUE THREAD

**Issue by artificialLeo** [mate-academy/kt-companion-object#7]
Please check [task requirements](https://github.com/mate-academy/kt-companion-object). You need to use 'companion object' inside class.
Also functionality may be simplified.
Please check this link
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/replace.html

_Originally posted by @StarchenkoM in https://github.com/mate-academy/kt-companion-object/pull/6#pullrequestreview-1975927097_

**Comment by artificialLeo** [comment]
Detekt don't let to do so!!!

**Comment by StarchenkoM** [comment]
Not an issue, as checkstyle library points on some possible syntax improvement in this particular situation which are not related to task requirements.
In case if project runs via IDE functionality there are correct execution and result.
